version: "3.9"
services:
  api:
    build: ./backend/api
    container_name: api
    ports:
      - '3000:8080'

  logic-mongodb:
    build: ./backend/mongoDB
    container_name: logic_mongodb
    ports:
      - '3001:8080'

  logic-postgresql:
    build: ./backend/postgreSQL
    container_name: logic_postgresql
    ports:
      - '3002:8080'

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./database/mongoDB:/data/db
    ports:
      - 27017:27017
    restart: always

  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database/postgreSQL:/var/lib/postgresql/data
    ports:
      - '5438:5432'
    restart: always