CREATE TABLE IF NOT EXISTS list (
  _id INT GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(96) NOT NULL,
  PRIMARY KEY(_id)
);

CREATE TABLE IF NOT EXISTS item (
  _id INT GENERATED ALWAYS AS IDENTITY,
  list_id INT,
  description VARCHAR(256) NOT NULL,
  checked BOOL DEFAULT 'f',
  PRIMARY KEY(_id),
  CONSTRAINT fk_list
      FOREIGN KEY(list_id) 
	  REFERENCES list(_id)
	  ON DELETE SET NULL
);
